### ISSUE TITLE
Various fixes not available

### ISSUE THREAD

**Issue by jstobern** [BlueCop/BlueCop-XBMC-Plugins#1]
Hi,

Thank you for your excellent addons.

This is a FYI. There are a number of community contributed fixes on the freecable video addon forum at xbmc.org that have not been incorporated into the "official" addon. Is it possible to scrape the forum for the latest fixes since your last release and push to them out to the world?

At the moment it seems like CBS, PBS, ABC, PBS Kids, USA today all have contributions to fix some station related issue.

Regards,
Jens.

**Comment by yultide** [comment]
where are the fixes?  if you get me a list of links, i can put them in fork & create a pull request for bluecorp.

**Comment by jstobern** [comment]
Looks like Bluecop if back on the XBMC video forums. I'm closing this considering all the work done by moneymaker, slices and zero on the maintenance of the Freecable and Hulu plugins.
